spring.application.name=zavrsni-rad
spring.profiles.active=dev
spring.jpa.open-in-view=true
server.tomcat.connection-timeout=20000
spring.mvc.async.request-timeout=20000
cloudinary.cloud-name=drkdx0qvh
cloudinary.api-key=422912596446664
cloudinary.api-secret=66F34pcVJmmjJqlRk1rbCNZHw5w
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB