spring.application.name=zavrsni-rad
spring.profiles.active=prod
spring.jpa.open-in-view=true
server.tomcat.connection-timeout=20000
spring.mvc.async.request-timeout=20000
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_KEY}
cloudinary.api-secret=${CLOUDINARY_SECRET}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.port=${PORT:8080}